### PR TITLE
Support OTP 17,18,19.

### PR DESCRIPTION
**Pull request by master-q**
How about supporting latest OTP?

### CODE REVIEW

**Comment by kuenishi** [comment]
Now Travis CI supports 19.0 and it would be great. But please fix test failure.

**Comment by master-q** [comment]
O.K. I'll try to fix it.

**Comment by zmstone** [comment]
Can someone please trigger a travis re-run ?

The first failure looks like a random-ish timeout.
And other two `already_started` failures seem connected to the previous failure.

The OTP-17 job failed for the same reasons as 19,
so it's very unlikely an issue newly introduced.

**Comment by zmstone** [comment]
And perhaps limit the number of OTP releases to verify against?
e.g. one latest path release for each major release ?

**Comment by kuenishi** [comment]
I am very sorry about my sabotage not retrying Travis test.

**Pull request merged**
